nodeLinker: node-modules

# Suppress peer dependency warnings for known compatible packages
peerDependencyRules:
  ignoreMissing:
    - "@types/react"
    - "@types/react-dom"
  allowedVersions:
    react: "18 || 19"
    react-dom: "18 || 19"
