[build]
  publish = ".next"
  command = "yarn install --frozen-lockfile --prefer-offline --network-timeout 120000 && npm rebuild sharp --platform=linux --arch=x64 && yarn build"

[build.environment]
  NODE_VERSION = "20"
  YARN_FLAGS = "--prefer-offline --network-timeout 120000 --silent"
  NODE_OPTIONS = "--no-deprecation --max-old-space-size=8192 --enable-source-maps=false"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_PRODUCTION = "false"
  # Optimize build performance
  YARN_CACHE_FOLDER = ".yarn/cache"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  # Disable source maps for faster builds
  GENERATE_SOURCEMAP = "false"
  # Skip optimizations for faster builds
  NODE_ENV = "production"
  # Skip TypeScript checking for speed
  SKIP_TYPE_CHECK = "true"

# Production context: all deploys from the Production branch
[context.production]
  publish = ".next"
  command = "yarn install --frozen-lockfile --prefer-offline --network-timeout 180000 && npm rebuild sharp --platform=linux --arch=x64 && yarn build"
  [context.production.environment]
    NODE_ENV = "production"
    NODE_OPTIONS = "--no-deprecation --max-old-space-size=4096"
    NPM_CONFIG_PRODUCTION = "false"

# Deploy Preview context: all Deploy Previews
[context.deploy-preview]
  publish = ".next"  
  command = "yarn install --frozen-lockfile --prefer-offline --network-timeout 300000 && npm rebuild sharp --platform=linux --arch=x64 && yarn build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"
    NODE_OPTIONS = "--no-deprecation --max-old-space-size=4096"
    NPM_CONFIG_PRODUCTION = "false"

# Branch deploy context: all deploys that are not from a pull/merge request or from the Production branch
[context.branch-deploy]
  publish = ".next"
  command = "yarn install --frozen-lockfile --prefer-offline --network-timeout 300000 && npm rebuild sharp --platform=linux --arch=x64 && yarn build"

# Next.js serverless functions
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for Next.js and SSH app
[[redirects]]
  from = "/ssh-app"
  to = "/ssh-app/"
  status = 301

[[redirects]]
  from = "/ssh-app/*"
  to = "/ssh-app/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = "public,max-age=31536000"

[[headers]]  
  for = "/*.png"
  [headers.values]
    cache-control = "public,max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    cache-control = "public,max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    cache-control = "public,max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    cache-control = "public,max-age=31536000"

[[headers]]
  for = "/*.ico"
  [headers.values]
    cache-control = "public,max-age=31536000"