name: Deploy to Netlify

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build project
        run: yarn build
        env:
          NODE_ENV: production
          NODE_OPTIONS: --no-deprecation
          NEXT_TELEMETRY_DISABLED: 1

      - name: Deploy to Netlify (production)
        if: github.event_name == 'push' && github.ref_name == 'main' && env.NETLIFY_AUTH_TOKEN != '' && env.NETLIFY_SITE_ID != ''
        uses: netlify/actions/cli@v4
        with:
          args: deploy --prod --build --message "GitHub Actions Production"
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

      - name: Deploy preview to Netlify (PR)
        if: github.event_name == 'pull_request' && env.NETLIFY_AUTH_TOKEN != '' && env.NETLIFY_SITE_ID != ''
        uses: netlify/actions/cli@v4
        with:
          args: deploy --build --alias pr-${{ github.event.number }} --message "PR #${{ github.event.number }} preview"
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

      - name: Deploy branch to Netlify (non-main)
        if: github.event_name == 'push' && github.ref_name != 'main' && env.NETLIFY_AUTH_TOKEN != '' && env.NETLIFY_SITE_ID != ''
        uses: netlify/actions/cli@v4
        with:
          args: deploy --build --alias ${{ github.ref_name }} --message "Branch ${{ github.ref_name }} deploy"
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}